version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
    - '80:80'
    volumes:
    - './nginx:/etc/nginx/conf.d'
    - static:/static-files
    depends_on:
    - web

  web:
    build: .
    command: sh run.sh
    volumes:
    - data:/data
    - static:/app/meetings/assets/static
    expose:
    - '8000'

volumes:
  data: {}
  static: {}